# This file defines regular peers. You will need one instance of a root peer and
# might want to play around with the replica count to scale your experiments.

deployment:
  replicaCount: 2
  image:
    repository: docker.io/yesoer/peersdb
    tag: latest

service:
  enable: false
  ip: 10.96.240.103

# use the node selector to deploy on specific nodes via label
nodeSelector:
  enable: false
  region: ""

# these parameters are passed down to the docker image and used as parameters
# for the binary execution
params:
  # whether the replicas should be root nodes 
  root: false
  # ip of the root peer, ip must match the one in root-peeer-values
  rootIP: "10.96.240.103"
