apiVersion: v1
kind: Service
metadata:
  name: peersdb-service
spec:
  type: ClusterIP
  {{ if .Values.service.setIP }}
  clusterIP: {{ .Values.service.ip }}
  {{ else }}
  clusterIP: None
  {{ end }}
  selector:
    app: peersdb
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: ipfs
      protocol: TCP
      port: 4001
      targetPort: 4001

